{% set name = "sounderpy" %}
{% set version = "3.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sounderpy-{{ version }}.tar.gz
  sha256: 2ca128b5ade94e8ebbe536e45fb9ad74430dd1b609eb951c704b710402fb7958

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68.0
    - pip
  run:
    - python >={{ python_min }}
    - arm_pyart >=1.16.1
    - cartopy >=0.21.0
    - cdsapi >=0.7.3
    - ecape >=0.1.1
    - ecape-parcel >=1.2.0.2
    - matplotlib-base >=3.3.0
    - metpy >=1.5.1
    - netcdf4 >=1.6.4
    - numpy >=1.20.0
    - pandas >=1.2.0
    # hack around mamba solver
    - s3fs >=2024.10.0
    - siphon >=0.9
    - scipy >=1.10.1
    - xarray >=0.18.0

test:
  imports:
    - sounderpy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Vertical Profile Data Retrieval and Analysis Tool For Python
  home: https://kylejgillett.github.io/sounderpy/
  dev_url: https://github.com/kylejgillett/sounderpy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
