{% set name = "sounderpy" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sounderpy-{{ version }}.tar.gz
  sha256: 1390d450d48a93c481093c792e834b2557253c6dd8b4f6b3498b36ec8812fb61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=68.0
    - pip
  run:
    - python >=3.8
    - cdsapi >=0.6.1
    - ecape >=0.1.1
    - matplotlib-base >=3.3.0,<=3.7.1
    - metpy >=1.5.1
    - netcdf4 >=1.6.4
    - numpy >=1.20.0
    - pandas >=1.2.0
    - siphon >=0.9
    - scipy >=1.10.1
    - xarray >=0.18.0

test:
  imports:
    - sounderpy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Vertical Profile Data Retrieval and Analysis Tool For Python
  home: https://kylejgillett.github.io/sounderpy/
  dev_url: https://github.com/kylejgillett/sounderpy
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - akrherz
