schema_version: 1

context:
  name: sounderpy
  version: "3.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/kylejgillett/sounderpy/archive/refs/tags/v${{ version }}.tar.gz
  sha256: e5a968334d5c78dce3862e53e86667057abf431448656cf8bf674e64edd9cabf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68.0
    - pip
  run:
    - python >=${{ python_min }}
    - arm_pyart >=2.0
    - beautifulsoup4
    - cartopy >=0.21.0
    - cdsapi >=0.7.3
    - cfgrib
    - ecape >=0.1.1
    - ecape-parcel >=1.2.0.2
    - eccodes
    - fsspec
    - matplotlib-base >=3.3.0
    - metpy >=1.5.1
    - netcdf4 >=1.6.4
    - numpy >=1.20.0
    - pandas >=1.2.0
    - pillow
    - pyproj
    - requests
    - s3fs
    - siphon >=0.11
    - scipy >=1.10.1
    - xarray >=0.18.0

tests:
  - python:
      imports:
        - sounderpy
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Vertical Profile Data Retrieval and Analysis Tool For Python
  license: MIT
  license_file: LICENSES
  homepage: https://kylejgillett.github.io/sounderpy/
  repository: https://github.com/kylejgillett/sounderpy

extra:
  recipe-maintainers:
    - akrherz
